sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=trunk WP_MULTISITE=0
  fast_finish: true

install:
  - composer install --no-interaction --optimize-autoloader --prefer-dist

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
      composer global require "phpunit/phpunit=4.8.*"
    else
      composer global require "phpunit/phpunit=5.7.*"
    fi
  - |
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  - phpcs
  - phpunit
